version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /CarBuiler
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
