version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn clean install

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Run JUnit Tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build

